window.PORTFOLIO_DATA = {
  projects: [
    {
      slug: "hmi",
      title: "HMI",
      status: "Case study being prepared",
      type: "HMI",
      image: "assets/projects/hmi-v2.png",
      summary: "An in-car HMI interface design project.",
      role: "Project details to be documented",
      ai: "Not applicable; archival professional work",
      known: "The visual preview is available. The project context, contribution, and outcomes will be added when the case study is ready.",
    },
    {
      slug: "goods",
      title: "Goods",
      status: "Case study being prepared",
      type: "APP",
      image: "assets/projects/goods-v2.png",
      summary: "A mobile app interface design project.",
      role: "Project details to be documented",
      ai: "Not applicable; archival professional work",
      known: "The visual preview is available. The project context, contribution, and outcomes will be added when the case study is ready.",
    },
    {
      slug: "mloan",
      title: "Mloan",
      status: "Case study being prepared",
      type: "APP / CRM",
      image: "assets/projects/mloan-v2.png",
      summary: "A mobile lending interface design project.",
      role: "Project details to be documented",
      ai: "Not applicable; archival professional work",
      known: "The visual preview is available. The project context, contribution, and outcomes will be added when the case study is ready.",
    },
    {
      slug: "cubicost-ptj",
      title: "Cubicost PTJ",
      status: "Case study being prepared",
      type: "DeskTop",
      image: "assets/projects/cubicost-ptj-v2.png",
      summary: "A desktop product interface design project.",
      role: "Project details to be documented",
      ai: "Not applicable; archival professional work",
      known: "The visual preview is available. The project context, contribution, and outcomes will be added when the case study is ready.",
    },
  ],
};
